"""add password hash

Revision ID: 1128a375f9bf
Revises: 71bc504b86f3
Create Date: 2026-04-24 12:37:37.759474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '1128a375f9bf'
down_revision: Union[str, Sequence[str], None] = '71bc504b86f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ##op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'passsword_hash', new_column_name='password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ##op.drop_column('users', 'password_hash')
    op.alter_column('users', 'password_hash', new_column_name='passsword_hash')
    # ### end Alembic commands ###
