
"""add roles to user

Revision ID: 7b8c6933fa6d
Revises: 78e6c0a5dd41
Create Date: 2026-05-04 08:45:58.783503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '7b8c6933fa6d'
down_revision: Union[str, Sequence[str], None] = '78e6c0a5dd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET last_name = 'Unknown'")
    op.alter_column('users', 'last_name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
